# Generated by Django 3.1.2 on 2020-10-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('uname', models.CharField(max_length=128)),
                ('profile_picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=250)),
                ('startDateTime', models.DateTimeField(max_length=250)),
                ('endDateTime', models.DateTimeField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('ccoded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colors')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('is_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
