# Generated by Django 3.1.3 on 2020-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201130_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='invite',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
